import { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { activeSession, dateKey, elapsedSeconds, formatClock, formatDuration } from '@/domain/logic';
import { useMiseStore } from '@/store/use-mise-store';
import { Button, Card, Field, Label, palette, Sub, Title } from '@/components/mise-ui';
import { notificationPermission } from '@/notifications/local-notifications';

type Tab = 'today' | 'schedule' | 'stats' | 'settings';

function TodoForm({ visible, close }: { visible: boolean; close: () => void }) {
  const add = useMiseStore((s) => s.addTodo); const [title, setTitle] = useState('');
  return <Modal visible={visible} transparent animationType="slide"><View style={s.overlay}><Card style={s.modal}><Title>새 Todo</Title><Field value={title} onChangeText={setTitle} placeholder="예: 통계 화면 구현" /><View style={s.row}><Button label="취소" tone="quiet" onPress={close} /><Button label="추가" onPress={async () => { await add(title); setTitle(''); close(); }} /></View></Card></View></Modal>;
}

function BlockForm({ visible, close }: { visible: boolean; close: () => void }) {
  const save = useMiseStore((s) => s.saveBlock); const todos = useMiseStore((s) => s.todos); const [title, setTitle] = useState(''); const [start, setStart] = useState('09:00'); const [end, setEnd] = useState('10:00'); const [todoId, setTodoId] = useState<string | null>(null);
  const minute = (input: string) => { const [h, m] = input.split(':').map(Number); return Number.isFinite(h) && Number.isFinite(m) ? h * 60 + m : -1; };
  return <Modal visible={visible} transparent animationType="slide"><View style={s.overlay}><Card style={s.modal}><Title>새 Schedule</Title><Field value={title} onChangeText={setTitle} placeholder="일정 제목" /><Label>시작 / 종료 (HH:MM)</Label><View style={s.row}><View style={s.flex}><Field value={start} onChangeText={setStart} placeholder="09:00" /></View><View style={s.flex}><Field value={end} onChangeText={setEnd} placeholder="10:00" /></View></View><Label>Todo 연결</Label><ScrollView horizontal contentContainerStyle={s.chips}>{todos.map((todo) => <Pressable key={todo.id} onPress={() => setTodoId(todo.id === todoId ? null : todo.id)} style={[s.chip, todoId === todo.id && s.chipOn]}><Text style={todoId === todo.id ? s.chipTextOn : s.chipText}>{todo.title}</Text></Pressable>)}</ScrollView><View style={s.row}><Button label="취소" tone="quiet" onPress={close} /><Button label="저장" onPress={async () => { const ok = await save({ dateKey: dateKey(), startMinute: minute(start), endMinute: minute(end), title, todoId }); if (ok) close(); }} /></View></Card></View></Modal>;
}

function Today({ addTodo }: { addTodo: () => void }) {
  const todos = useMiseStore((x) => x.todos); const sessions = useMiseStore((x) => x.sessions); const blocks = useMiseStore((x) => x.blocks); const toggle = useMiseStore((x) => x.toggleTodo); const toggleToday = useMiseStore((x) => x.toggleToday); const remove = useMiseStore((x) => x.deleteTodo); const start = useMiseStore((x) => x.startSession); const key = dateKey();
  const listed = todos.filter((todo) => todo.todayDateKeys.includes(key)); const seconds = sessions.filter((session) => session.status === 'completed' && session.type === 'focus' && session.localStartDate === key).reduce((sum, session) => sum + (session.recordedSeconds ?? 0), 0); const next = blocks.filter((block) => !block.deletedAt && block.dateKey === key).sort((a,b) => a.startMinute-b.startMinute)[0];
  return <ScrollView contentContainerStyle={s.content}><Label>{key}</Label><Title>오늘의 Mise</Title><Sub>계획을 세우고 실제 시간을 남겨보세요.</Sub><Card><Label>오늘 Focus</Label><Text style={s.big}>{formatDuration(seconds)}</Text><Sub>{next ? `다음 일정 · ${formatClock(next.startMinute)} ${next.title}` : '다음 일정이 없습니다.'}</Sub></Card><View style={s.head}><Title>오늘 할 일</Title><Button label="+ 추가" onPress={addTodo} /></View>{listed.map((todo) => <Card key={todo.id} style={s.todo}><Pressable onPress={() => toggle(todo.id)} style={[s.check, todo.status === 'completed' && s.checked]}>{todo.status === 'completed' && <Text style={{color:'#fff'}}>✓</Text>}</Pressable><View style={s.flex}><Text style={[s.todoTitle, todo.status === 'completed' && s.done]}>{todo.title}</Text><Sub>{todo.parentId ? '하위 Todo' : '프로젝트'}</Sub></View><Pressable onPress={() => start('focus', todo.id).then((sessionId) => sessionId && router.push('/timer'))}><Text style={s.action}>집중</Text></Pressable><Pressable onPress={() => Alert.alert('Todo 메뉴', todo.title, [{text:'오늘에서 제외', onPress:()=>toggleToday(todo.id,key)},{text:'삭제',style:'destructive',onPress:()=>remove(todo.id)},{text:'취소',style:'cancel'}])}><Text style={s.menu}>···</Text></Pressable></Card>)}{!listed.length && <Card><Sub>오늘 할 일을 추가해 보세요.</Sub></Card>}<Button label="휴식 시작" tone="quiet" onPress={() => start('short_break').then((sessionId) => sessionId && router.push('/timer'))} /></ScrollView>;
}

function Schedule({ addBlock }: { addBlock: () => void }) {
  const blocks = useMiseStore((x) => x.blocks); const todos = useMiseStore((x) => x.todos); const remove = useMiseStore((x) => x.deleteBlock); const start = useMiseStore((x) => x.startSession); const [picker, setPicker] = useState<string | null>(null); const list = blocks.filter((block) => block.dateKey === dateKey() && !block.deletedAt).sort((a,b) => a.startMinute-b.startMinute);
  return <ScrollView contentContainerStyle={s.content}><Label>{dateKey()}</Label><Title>하루 시간표</Title><Sub>겹치지 않는 5분 단위 계획입니다.</Sub><Button label="+ 일정 추가" onPress={addBlock} />{list.map((block) => <Card key={block.id}><View style={s.head}><Text style={s.time}>{formatClock(block.startMinute)} — {formatClock(block.endMinute)}</Text><Pressable onPress={() => remove(block.id)}><Text style={s.delete}>삭제</Text></Pressable></View><Text style={s.todoTitle}>{block.title}</Text><Sub>{block.todoId ? todos.find((todo) => todo.id === block.todoId)?.title ?? '삭제된 Todo' : 'Todo 미연결'}</Sub><Button label="Focus 시작" onPress={() => block.todoId ? start('focus', block.todoId, block.id).then((sessionId) => sessionId && router.push('/timer')) : setPicker(block.id)} /></Card>)}{!list.length && <Card><Sub>등록된 일정이 없습니다.</Sub></Card>}<Modal visible={!!picker} transparent animationType="slide"><View style={s.overlay}><Card style={s.modal}><Title>Todo 선택</Title>{todos.map((todo) => <Button key={todo.id} label={todo.title} tone="quiet" onPress={() => picker && start('focus', todo.id, picker).then((sessionId) => { setPicker(null); if (sessionId) router.push('/timer'); })} />)}<Button label="취소" tone="quiet" onPress={() => setPicker(null)} /></Card></View></Modal></ScrollView>;
}

function Stats() {
  const sessions = useMiseStore((x) => x.sessions); const blocks = useMiseStore((x) => x.blocks); const todos = useMiseStore((x) => x.todos); const completed = sessions.filter((session) => session.status === 'completed'); const focus = completed.filter((session) => session.type === 'focus'); const focusSeconds = focus.reduce((sum, session) => sum + (session.recordedSeconds ?? 0), 0); const breakSeconds = completed.filter((session) => session.type !== 'focus').reduce((sum, session) => sum + (session.recordedSeconds ?? 0), 0); const snapshots = new Map<string, NonNullable<typeof sessions[number]['scheduleSnapshot']>>(); completed.forEach((session) => { if (session.scheduleBlockId && session.scheduleSnapshot) snapshots.set(session.scheduleBlockId, session.scheduleSnapshot); }); const plannedSeconds = blocks.filter((block) => !block.deletedAt).reduce((sum, block) => sum + (block.endMinute - block.startMinute) * 60, 0) + [...snapshots.values()].reduce((sum, snapshot) => sum + (snapshot.plannedEndMinute - snapshot.plannedStartMinute) * 60, 0);
  return <ScrollView contentContainerStyle={s.content}><Label>이번 주</Label><Title>시간 회고</Title><View style={s.grid}><Card style={s.flex}><Label>FOCUS</Label><Text style={s.stat}>{formatDuration(focusSeconds)}</Text></Card><Card style={s.flex}><Label>BREAK</Label><Text style={s.stat}>{formatDuration(breakSeconds)}</Text></Card></View><Card><Label>계획 대비 실제</Label><Text style={s.big}>{formatDuration(focusSeconds)} <Text style={s.muted}>/ {formatDuration(plannedSeconds)}</Text></Text></Card><Title>Todo별 기록</Title>{todos.map((todo) => { const value = focus.filter((session) => session.todoId === todo.id).reduce((sum, session) => sum + (session.recordedSeconds ?? 0), 0); return value ? <Card key={todo.id}><Text style={s.todoTitle}>{todo.title}</Text><Text style={s.stat}>{formatDuration(value)}</Text></Card> : null; })}</ScrollView>;
}

function Settings() {
  const settings = useMiseStore((x) => x.settings); const update = useMiseStore((x) => x.updateSettings); const reset = useMiseStore((x) => x.reset);
  const [permission, setPermission] = useState('미결정');
  return <ScrollView contentContainerStyle={s.content}><Label>LOCAL PROTOTYPE</Label><Title>설정</Title><Card><Label>타이머</Label>{([['Focus', 'defaultFocusMinutes'], ['Short Break', 'shortBreakMinutes'], ['Long Break', 'longBreakMinutes']] as const).map(([label, key]) => <View key={key} style={s.setting}><Text>{label}</Text><View style={s.row}><Pressable onPress={() => update({ [key]: Math.max(1, settings[key] - 5) })}><Text style={s.step}>−</Text></Pressable><Text style={s.minute}>{settings[key]}분</Text><Pressable onPress={() => update({ [key]: settings[key] + 5 })}><Text style={s.step}>+</Text></Pressable></View></View>)}</Card><Card><Label>표시·알림</Label><View style={s.setting}><Text>카운트다운</Text><Switch value={settings.timerMode === 'countdown'} onValueChange={(value) => update({ timerMode: value ? 'countdown' : 'elapsed' })} /></View><View style={s.setting}><Text>Focus 종료 알림</Text><Switch value={settings.focusNotificationEnabled} onValueChange={(value) => update({ focusNotificationEnabled: value })} /></View><View style={s.setting}><Text>Break 종료 알림</Text><Switch value={settings.breakNotificationEnabled} onValueChange={(value) => update({ breakNotificationEnabled: value })} /></View><Sub>알림 권한: {permission}</Sub><Button label="알림 권한 요청" tone="quiet" onPress={async () => setPermission(await notificationPermission())} /></Card><Card><Label>계정</Label><Text style={s.todoTitle}>Mock 사용자</Text><Sub>OAuth 연결은 서버 단계에서 추가됩니다.</Sub></Card><Button label="샘플 데이터 초기화" tone="danger" onPress={() => Alert.alert('초기화', '이 기기의 데이터를 초기화할까요?', [{ text:'취소', style:'cancel' }, { text:'초기화', style:'destructive', onPress: reset }])} /></ScrollView>;
}

export default function Home() {
  const hydrate = useMiseStore((x) => x.hydrate); const hydrated = useMiseStore((x) => x.hydrated); const sessions = useMiseStore((x) => x.sessions); const error = useMiseStore((x) => x.error); const [tab, setTab] = useState<Tab>('today'); const [todoForm, setTodoForm] = useState(false); const [blockForm, setBlockForm] = useState(false); const [now, setNow] = useState(Date.now());
  useEffect(() => { hydrate(); }, [hydrate]); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []); if (!hydrated) return <SafeAreaView style={s.center}><Text>데이터를 준비하고 있어요…</Text></SafeAreaView>;
  const current = activeSession(sessions); return <SafeAreaView style={s.safe}><View style={s.app}>{tab === 'today' && <Today addTodo={() => setTodoForm(true)} />}{tab === 'schedule' && <Schedule addBlock={() => setBlockForm(true)} />}{tab === 'stats' && <Stats />}{tab === 'settings' && <Settings />}{current && <Pressable onPress={() => router.push('/timer')} style={s.mini}><Text style={s.miniText}>{current.type === 'focus' ? '집중 중' : '휴식 중'} · {formatDuration(elapsedSeconds(current, now))}</Text><Text style={{color:'#fff'}}>열기 ›</Text></Pressable>}<View style={s.tabs}>{([['today','오늘'],['schedule','일정'],['stats','통계'],['settings','설정']] as const).map(([id,label]) => <Pressable key={id} onPress={() => setTab(id)} style={s.tab}><Text style={[s.tabText, tab === id && s.tabOn]}>{label}</Text></Pressable>)}</View></View><TodoForm visible={todoForm} close={() => setTodoForm(false)} /><BlockForm visible={blockForm} close={() => setBlockForm(false)} />{error && <Pressable onPress={() => useMiseStore.setState({ error:null })} style={s.toast}><Text style={{color:'#fff'}}>{error}</Text></Pressable>}</SafeAreaView>;
}
const s = StyleSheet.create({ safe:{flex:1,backgroundColor:palette.bg},app:{flex:1},content:{padding:20,paddingBottom:130,gap:14},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:palette.bg},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},row:{flexDirection:'row',gap:10,alignItems:'center'},flex:{flex:1},big:{fontSize:28,fontWeight:'800',color:palette.ink},muted:{color:palette.muted,fontSize:16},todo:{flexDirection:'row',alignItems:'center'},check:{width:25,height:25,borderRadius:8,borderWidth:2,borderColor:palette.green,alignItems:'center',justifyContent:'center'},checked:{backgroundColor:palette.green},todoTitle:{color:palette.ink,fontWeight:'700',fontSize:16},done:{textDecorationLine:'line-through',color:palette.muted},action:{color:palette.green,fontWeight:'800'},menu:{color:palette.muted,fontSize:18,paddingHorizontal:4},time:{color:palette.green,fontWeight:'800'},delete:{color:palette.red,fontWeight:'700'},overlay:{flex:1,justifyContent:'flex-end',backgroundColor:'#0008',padding:16},modal:{gap:14},chips:{gap:8},chip:{paddingHorizontal:12,paddingVertical:9,borderRadius:99,backgroundColor:palette.greenSoft},chipOn:{backgroundColor:palette.green},chipText:{color:palette.green,fontWeight:'700'},chipTextOn:{color:'#fff',fontWeight:'700'},grid:{flexDirection:'row',gap:12},stat:{fontSize:20,fontWeight:'800',color:palette.ink},setting:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',minHeight:44},step:{fontSize:25,fontWeight:'700',color:palette.green,paddingHorizontal:8},minute:{minWidth:48,textAlign:'center',fontWeight:'700'},mini:{position:'absolute',left:14,right:14,bottom:64,backgroundColor:palette.green,borderRadius:15,padding:14,flexDirection:'row',justifyContent:'space-between'},miniText:{color:'#fff',fontWeight:'800'},tabs:{height:58,borderTopWidth:1,borderColor:palette.line,backgroundColor:'#fff',flexDirection:'row'},tab:{flex:1,alignItems:'center',justifyContent:'center'},tabText:{color:palette.muted,fontWeight:'700'},tabOn:{color:palette.green},toast:{position:'absolute',bottom:78,left:18,right:18,padding:14,borderRadius:12,backgroundColor:palette.red} });
